name: Deploy on Ubuntu
description: Deploy on Ubuntu Linux
runs:
  using: composite
  steps:
    - name: Prepare environment
      shell: bash
      run: |
        echo "SUDO=$SUDO" >> $GITHUB_ENV
        if [[ -z "$SUDO" ]]; then
        echo "Fixing HOME to /root (was '$HOME')"
        export HOME=/root
        echo "HOME=$HOME" >> $GITHUB_ENV
        fi
        cd $HOME
        
        # arch
        export ARCH=amd64
        export PREFIX=x86_64-linux-gnu
        
        if [[ "$CI_DEPLOY_PLATFORM" == "linux-x86_64" ]]; then
          export ARCH=amd64
          export PREFIX=x86_64-linux-gnu
        elif [[ "$CI_DEPLOY_PLATFORM" == "linux-x86" ]]; then
          export ARCH=i386
          export PREFIX=i686-linux-gnu
        fi
        
        echo "ARCH=$ARCH" >> $GITHUB_ENV
        echo "PREFIX=$PREFIX" >> $GITHUB_ENV
        
        $SUDO dpkg --list
        $SUDO apt-get update
        
        # install basic packages
        echo "Installing basic tools [wget/curl/unzip/tar/git/patch]..."
        $SUDO apt-get -y install wget curl unzip tar git patch
        
        # install CMake
        echo "Installing CMake..."
        curl -LO https://github.com/Kitware/CMake/releases/download/v3.24.2/cmake-3.24.2-linux-x86_64.tar.gz
        $SUDO tar -xzf cmake-3.24.2-linux-x86_64.tar.gz -C /opt/
        $SUDO ln -sf /opt/cmake-3.24.2-linux-x86_64/bin/* /usr/bin/
        
        # install OpenJDK 8 & Maven
        echo "Installing OpenJDK 8 and Maven..."
        $SUDO apt-get -y install openjdk-8-jdk
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
        ln -sf $JAVA_HOME /usr/lib/jvm/default-java
        find /usr/lib/jvm/default-java/
        
        curl -LO https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
        $SUDO tar -xzf apache-maven-3.6.3-bin.tar.gz -C /opt/
        $SUDO ln -sf /opt/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
        
        # decide maven phase
        MAVEN_PHASE=install
        
    - name: Build project
      shell: bash
      run: |
        git --version
        cmake --version
        mvn --version
        
        df -h
        
        echo "Cloning source codes from GitHub"
        git clone --depth 1 https://github.com/JavaLLM/javacpp-presets
        
        mkdir -p $HOME/.m2
        
        export MAKEJ=$(getconf _NPROCESSORS_ONLN)
        
        echo "Executing Maven $MAVEN_PHASE on $MAKEJ processors"
        export EXT=${{ matrix.ext }}
        export EXT2=${EXT:1}
        export MAVEN_OPTS="-Xss2m -Xmx4g"
        export MAVEN_OPTIONS="clean $MAVEN_PHASE -B -U -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.count=3 -Djavacpp.platform=$CI_DEPLOY_PLATFORM $MAVEN_OPTS $CI_DEPLOY_OPTIONS"
        
        # process preset
        echo "Building presets..."
        for i in {1..5}; do STATUS=0; mvn $MAVEN_OPTIONS -pl .,$CI_DEPLOY_MODULE && break || STATUS=$? && sleep 60; done; (exit $STATUS)
        # process platform
        echo "Build platform..."
        for i in {1..5}; do STATUS=0; mvn $MAVEN_OPTIONS -f $CI_DEPLOY_MODULE/platform/$EXT2/pom.xml && break || STATUS=$? && sleep 60; done; (exit $STATUS)
        
        echo "Built successfully"