name: llamacpp
on:
  push:
    paths:
      - llamacpp/**
      - .github/workflows/llamacpp.yml
env:
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
jobs:
  linux-x86_64:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ext: [ "" ]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions

  macosx-arm64:
    runs-on: macos-11
    strategy:
      matrix:
        ext: [ "" ]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions

  macosx-x86_64:
    runs-on: macos-11
    strategy:
      matrix:
        ext: [ "" ]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions