name: llamacpp
on:
  push:
    paths:
      - llamacpp/**
      - .github/workflows/llamacpp.yml
env:
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
jobs:
  linux-x86_64:
    runs-on: ubuntu-20.04
    steps:
      - uses: javallm/javacpp-presets/.github/actions/deploy-ubuntu@actions

